name: Generate VoronUsers README.md
author: FHeilmann
description: This action searches for .metadata.yml files in a specific folder, and generates a Readme file in said folder
branding:
  icon: 'hard-drive'
  color: 'red'
inputs:
  target_directory:
    description: Name of the directory in which the printer mods are located and where README.md is generated
    type: string
    required: true
    default: printer_mods
  github_token:
    description: 'GitHub token or PAT token'
    required: true
    default: ${{github.token}}
  commit_msg:
    description: "Commit message to use (don't forget to add [skip ci])"
    type: string
    required: true
    default: "Generate VoronUsers printer_mods README.md [skip ci]"
  commit_user:
    description: "Commit username to use"
    type: string
    required: true
    default: "Readme-Committer"
  commit_email:
    description: "Commit eMail to use"
    type: string
    required: true
    default: "readme@commit.me"
  preview:
    description: "Whether to only preview the README.md file"
    type: boolean
    required: true
    default: true
  python_cache_key:
    description: Cache key for a python installation that already contains the required dependencies
    type: string
    required: false
runs:
  using: "composite"
  steps:
    - name: Setup Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - if: ${{ inputs.python_cache_key != '' }}
      name: Get python package cache 🧰
      uses: actions/cache/restore@v3
      id: cache-python
      env:
        cache-name: cache-python
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ inputs.python_cache_key }}
    - if: ${{ steps.cache-python.outputs.cache-hit != 'true' }}
      name: Install PyYAML
      run: |
        pip install pyyaml
      shell: bash
    - name: Generate README.md
      run: |
        cd ${{inputs.target_directory}}
        export PREVIEW=${{inputs.preview}}
        python ${{github.action_path}}/generate_readme.py >> $GITHUB_STEP_SUMMARY
      shell: bash
    - name: Commit files
      if: ${{ inputs.preview == 'false' }}
      run: |
        git config --local user.email ${{inputs.commit_email}}
        git config --local user.name ${{inputs.commit_user}}
        git add ${{inputs.target_directory}}/README.md
        git commit -m "${{inputs.commit_msg}}" || true
      shell: bash
    - name: Push changes
      if: ${{ inputs.preview == 'false' }}
      uses: ad-m/github-push-action@master
      with:
        directory: ${{inputs.target_directory}}
        github_token: ${{inputs.github_token}}
        branch: ${{github.ref}}
